service: airtable-button
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  environment:
    AIRTABLE_KEY: ${ssm:/${self:provider.stage}/${self:service}/airtable/key~true}
    AIRTABLE_BASE: ${ssm:/${self:provider.stage}/${self:service}/airtable/base~true}
    AIRTABLE_TABLE: ${ssm:/${self:provider.stage}/${self:service}/airtable/table~true}
    SENTRY_DSN: ${ssm:/${self:provider.stage}/${self:service}/sentry/dsn~true}
  stackTags:
    project: airtable-button
    environment: prod
  tags:
    project: airtable-button
    environment: prod

functions:
  handle:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: api
          method: get
          cors: true
      - http:
          path: api
          method: post
          cors: true
